# ServerDefault
# The default PVP value of the server.
# Will be used as the PVP value unless overridden by world or player.
# Default: false
# Must be a boolean value (true or false).
Localisation Filename: localisation.yml
Debug: false

Server:
  Default: false
  Worlds:
    ExampleWorld: true
    ExampleWorld2:
      Default: false
      Players:
        AS1LV3RN1NJA: true
        skillchickenz75: false
    ExampleWorld3: true
    ExampleWorld4: false