author: JamesHealey94
website: https://github.com/JamesHealey94

name: SimplePVPToggle
main: com.gmail.jameshealey1994.simplepvptoggle.SimplePVPToggle
version: 0.1

commands:
    spt:
        aliases: [pvp, pvptoggle, simplepvptoggle, togglepvp]
        usage: Command used incorrectly! Use /<command> help for help!
permissions:
    spt.change.self:
        description: Allows you to change your PVP status for that world
        default: false
    spt.change.others:
        description: Allows you to change someone elses PVP status for that world
        default: false

    spt.setworlddefault:
        description: Allows you to set the default PVP status of that world
        default: false
    spt.setserverdefault:
        description: Allows you to set the default PVP status of the server
        default: false

    spt.status.self:
        description: Allows you to see your own PVP status
        default: false
    spt.status.others:
        description: Allows you to see the PVP status of other players
        default: false

    spt.info:
        description: Allows you to see the default PVP status of the server and it's worlds
        default: false

    spt.debug:
        description: Allows you to change the status of debug mode
        default: false

    spt.reload:
        description: Allows you to reload the config
        default: false