author: JamesHealey94
website: https://github.com/JamesHealey94

name: SimplePVPToggle
main: com.gmail.jameshealey1994.simplepvptoggle.SimplePVPToggle
version: 0.1

commands:
    spt:
        aliases: [pvp, pvptoggle, simplepvptoggle, togglepvp]
        usage: Command used incorrectly! Use /<command> help for help!
permissions:
    spt.*:
        description: Gives access to all commands
        default: false
        children:
            spt.change.*: true
            spt.setdefault.*: true
            spt.reload: true

    spt.change.*:
        description: Gives access to all toggle commands
        default: false
        children:
            spt.change.self: true
            spt.change.other: true
    spt.change.self:
        description: Allows you to change your PVP status for that world
        default: false
    spt.change.other:
        description: Allows you to change someone elses PVP status for that world
        default: false

    spt.setdefault.*:
        description: Gives access to all setdefault commands
        default: false
        children:
            spt.setdefault.world: true
            spt.setdefault.server: true
    spt.setdefault.world:
        description: Allows you to set the default PVP status of that world
        default: false
    spt.setdefault.server:
        description: Allows you to set the default PVP status of the server
        default: false

    spt.reload:
        description: Allows you to reload the config
        default: false